name: Linting and Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
  push:
    branches:
      - main

jobs:
  lint-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun i
      - run: bun lint
      - run: bun test
